### ISSUE TITLE
Where should write config?

### ISSUE THREAD

**Issue by Mds92** [Kukks/ts-nameof-loader#1]
Where should I write the following in an Angular 4 project

```javascript
{ 
	test: /\.ts$/i,
	use: ['awesome-typescript-loader', 'ts-nameof-loader']
}
```

We have to use `ng serve` in angular project, where should we use your config?
I get the following error without using your config:
`ERROR in D:/Sources/.../user.component.ts (108,48): Cannot find name 'nameof'.` when I used `ng serve`

**Comment by Kukks** [comment]
Not sure how NG4 is structured but from what I read they use Webpack. 

Look for the webpack.config file and ass the `ts-nameof-loader` to the ts test rule.

Then again I also found this https://github.com/angular/angular-cli/issues/1656 so they seem to hide the webpack config stuff behind their cli so you may want to read through it.

**Comment by Kukks** [comment]
@Mds92 Some further poking around got me these on how to get the webpack config exposed:
1. https://stackoverflow.com/questions/41549318/where-is-the-webpack-config-js-in-angular-cli-new-project
2. http://www.dzurico.com/angular-cli-with-the-super-powers/
